group.id=group
client.id=consumer-3

group.protocol=classic
#group.protocol=consumer

# Eager Classic Protocol
partition.assignment.strategy=org.apache.kafka.clients.consumer.RangeAssignor

# Cooperative Classic Protocol
#partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor
